apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <appname>-clusteragent
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: <appname>-clusteragent
    spec:
      containers:
      - env:
        - name: APPLICATION_NAME
          value: "<app name>"
        - name: TIER_NAME
          value: "K8SClusterAgent"
        - name: CONTROLLER_PORT
          value: "<port num: use 443 for saas ssl>"
        - name: CONTROLLER_HOST
          value: "<[account].saas.appdynamics.com>"
        - name: ACCOUNT_ACCESS_KEY
          value: "<account_access_key>"
        - name: ACCOUNT_NAME
          value: "<account_name>"
        - name: APPD_ANALYTICS_MONITOR
          value: "false"
        - name: APPD_DOCKER_VISIBILITY
          value: "false"
        - name: MACHINE_AGENT_PROPERTIES
          value: 
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: <docker image location>
        envFrom:
          - configMapRef:
              name: env-map
        imagePullPolicy: Always
        name: <appname>-clusteragent
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: false
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/lib/docker/containers
          name: docker-containers
        - mountPath: /var/log
          name: docker-logs
        - mountPath: /project
          name: project
        - mountPath: /appdynamics
          name: appdynamics
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: docker-containers
        hostPath:
          path: /var/lib/docker/containers
          type: Directory
      - name: docker-logs
        hostPath:
            path: /var/log
            type: Directory
      - name: project
      - name: appdynamics
